### ISSUE TITLE
Moderate reactions

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot2-discord#8]
I've not found public discord bots that can do this so I'll suggest it here.

Would be useful to have some basic moderation for reactions, where discord doesn't provide such functionality natively.

Namely, restricting the choice of emote. So e.g. if you had a channel like `#surveys` where people are only supposed to react with `VoteYea` or `VoteNay`, the bot would listen to reactions and remove them again if somebody reacts with an emote other than those two.

Possibly a per-channel setting, and maybe an option to override them per-message somehow.

Right off the top of my head I can think of two ways:

1. By detecting a special string at the end of the message like "Allowed Reactions: &lt;list of emotes>"
2. By allowing the post creator or server admins/moderators react to the message (their emote would not get removed) and then other people can also click on that emote and it won't get removed if an admin has previously used it - sort of like the "add reactions" permission

Override system like that should also maybe be a channel setting, especially if behaviour 2 is implemented, then it would be nicer to be able to toggle that kind of override system off

**Comment by pajlada** [comment]
Added a feature that I think will accomplish the same idea: the AUTO REACT system
https://github.com/pajbot/pajbot2-discord/commit/a51b90226c095f999416ba8d0316b9a52de8672a
